### PR TITLE
EN 16931 tags

### PR DESCRIPTION
**Pull request by apardods**
Added tags for GOBL objects mapping them to their correspondent EN 16931 Business Term (BT) or Business Group (BG).

### CODE REVIEW

**Review by cavalle — APPROVED** [review]
Nice!! I had exactly the same idea a few days ago

**Review by samlown — CHANGES_REQUESTED** [review]
The code itself looks sound, but I'm afraid this isn't the best approach. The fundamental issue is that the EN16931 semantic codes usually have a context, whereas the syntax defined in the GOBL structures are designed to be used anywhere.

The objective however is sound, its just the approach that needs changing. In my opinion there should be a table of EN16931 codes to JSON pointers/paths of attributes inside GOBL structures so that you always have a context. This table should also define "notes" or something similar to describe any additional implications or meanings. The mapping table should also be adjusted when addons or regimes are applied.

This might be a good subject to brainstorm next week.

**Comment by cavalle** [comment]
It's a good point that GOBL structs have a scope that could potentially exceed that of EN16391 and putting the metadata directly in the structs, while convenient, may not makes any sense in other contexts.

It's also true that mapping may not always be direct or trivial and additional notes to indicate special details may also be useful or necessary.

**Comment by urakozz** [comment]
Thank you for this PR, it's more comprehensive than FacturX documentation 😄

**Comment by samlown** [comment]
Closing this one in favor of #401

**Pull request closed without merging**
