### PR TITLE
Add UUIDv3 creation functions

### PR DESCRIPTION
**Pull request by cavalle**
* Useful to create UUIDs from other external identifiers deterministically

### CODE REVIEW

**Review by samlown — COMMENTED** [review]
I think I'd suggest adding some tests for these cases! :-) Since we're here, it might also make senes to support UUIDv5, and also add some comments about the differences. (v3 is faster, but less secure apparently)

**Comment by cavalle** [comment]
> I think I'd suggest adding some tests for these cases! :-) Since we're here, it might also make sense to support UUIDv5, and also add some comments about the differences. (v3 is faster, but less secure apparently)

Thanks! I'll do all that

**Comment by cavalle** [comment]
Just realised the comments aren't correct. A hash can never be "reversed", I'll fix it

**Comment by cavalle** [comment]
Fixed in: b90dc64

**Pull request merged**
